### ISSUE TITLE
TWRP 3.4 bricked my SM-G900F

### ISSUE THREAD

**Issue by 7RST1** [TeamWin/android_device_samsung_klte#5]
When installed through TWRP locally with downloaded image. When it rebooted first time, it booted as normal. However second time, when trying to boot to recovery via advanced reboot on LinageOS it wouldn't start either system or recovery. It got stuck in download mode with the error message "Could not perform normal boot".

**Comment by bigbiff** [comment]
Thanks for the report. I have removed the image from the site.

**Comment by ichernev** [comment]
@7RST1 was the brick reversible? Or the device is gone now :/

**Comment by 7RST1** [comment]
@ichernev  No, used Heimdall to recover it. Just had to flash recovery.

**Comment by Yilliee** [comment]
This problem has been fixed in the latest build so I think that this issue can be closed

**Comment by 7RST1** [comment]
Can confirmed fixed👍
